### ISSUE TITLE
Supplementary materials missing 

### ISSUE THREAD

**Issue by yxw9636** [facebookresearch/DeepSDF#10]
Hi Authors,

I'm reading the DeepSDF paper and I found a lot of details are presented in the supplementary materials. However when I tried to download the supplementary, I found that the link is broken:

http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Park_DeepSDF_Learning_Continuous_CVPR_2019_supplemental.pdf

Could you upload the supplementary online as well?

Thanks so much for your help!

**Comment by jjparkcv** [comment]
Hi, if you download the pdf file and change the extension to .zip you can open it.

**Comment by yxw9636** [comment]
I see. Now I got it. Thanks for the reply :)

**Comment by csyhping** [comment]
Hi, I can not download the supp.pdf from the link [](http://openaccess.thecvf.com/content_CVPR_2019/supplemental/Park_DeepSDF_Learning_Continuous_CVPR_2019_supplemental.pdf), it says "the pdf file cannot be loaded", what should i do ?

**Comment by csyhping** [comment]
Oh its my browser setting issue, already fix it.
