### ISSUE TITLE
Fail to make -j

### ISSUE THREAD

**Issue by Eric-Gty** [facebookresearch/DeepSDF#103]
Hi there, thanks for your work. 

I'm meeting a problem with the make step for generating the executable files. Based on other issues, I'm using the Pangolin v0.6. When trying to compile the DeepSDF, the error is as follows:

(graph) a@b:/mnt/data/allusers/shuaibi/DeepSDF/build$ make -j
[ 14%] Built target cnpy
[ 28%] Built target cnpy-static
[ 42%] Built target example1
[ 50%] Linking CXX executable ../bin/PreprocessMesh
/usr/bin/ld: CMakeFiles/PreprocessMesh.dir/src/PreprocessMesh.cpp.o: undefined reference to symbol '_ZNK8pangolin12OpenGlMatrix7InverseEv'
//usr/local/lib/libpango_opengl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/PreprocessMesh.dir/build.make:134: recipe for target '../bin/PreprocessMesh' failed
make[2]: *** [../bin/PreprocessMesh] Error 1
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/PreprocessMesh.dir/all' failed
make[1]: *** [CMakeFiles/PreprocessMesh.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2.

The system is Ubuuntu 18.04, with GCC and G++ as 8.4.0. I tried to use v0.6, v0.7, v0.8 versions of Pangolin but they all didn't work. 

If anyone with the similar setting that successfully compile this, please kindly tell me about your GCC and G++ version, and the Pangolin version that you used. Thanks a lot.

**Comment by Eric-Gty** [comment]
Solved with Pangolin-0.7, GCC, and G++ 8.4.0. Use cmake .. -DCMAKE_CXX_STANDARD=17 for compiling the DeepSDF

**Comment by GetOverMassif** [comment]
Solved! Thanks a lot

**Comment by GetOverMassif** [comment]
> Solved with Pangolin-0.7, GCC, and G++ 8.4.0. Use cmake .. -DCMAKE_CXX_STANDARD=17 for compiling the DeepSDF

Solved! Thanks a lot
