### ISSUE TITLE
Visualize pre-processed SDF values as mesh

### ISSUE THREAD

**Issue by nicolasugrinovic** [facebookresearch/DeepSDF#15]
Hi thank you for your code and support with the issues. 
Is there a way to visualize the mesh that results from the pre-processing stage? The output of preprocess_data.py is only SDF values. It there a way to get a mesh from these "GT" values?

Thanks

**Comment by tschmidt23** [comment]
The SDF samples are simply point samples with no connectivity information. One way to visualize the samples is to plot all the negative samples in 3D, which should indicate the shape.

**Comment by nicolasugrinovic** [comment]
Thank you for the answer. I have done that already but it is difficult to visualize the quality of the sampling this way. 
Are any of these params, found in PreprocessMesh.cpp, of any help?
```
  app.add_option("--ply", plyFileNameOut, "Save ply pc to here");
  app.add_flag("--sply", save_ply, "save ply point cloud for visualization");
```
I tried to set them through through, but got nothing in return. 
Thanks!

**Comment by tschmidt23** [comment]
I've just pushed a simple visualization in 55ff69c. It should show all the point samples with negative SDF value (i.e. all samples that lie inside the shape). You'll need to have the pypangolin module from the Pangolin project built and on your python path to run it.

Hope it's helpful!

**Comment by nicolasugrinovic** [comment]
Great, thanks a lot!
