### ISSUE TITLE
Headless rendering while preprocessing meshes

### ISSUE THREAD

**Issue by martinruenz** [facebookresearch/DeepSDF#18]
I would suggest to by default execute pangolin headlessly, when preprocessing meshes, in order to avoid windows popping up (that steal the focus and make the PC unusable during the processing otherwise).

Something like this should do:
```
envir = os.environ.copy()
envir["PANGOLIN_WINDOW_URI"] = "headless://"
subproc = subprocess.Popen(command, stdout=subprocess.DEVNULL, env=envir)
```

Alternatively, one could mention that `export PANGOLIN_WINDOW_URI=headless://` exists in the README.

**Comment by tschmidt23** [comment]
Headless rendering adds an additional requirement on EGL which will not be available for everyone. Given the headaches that the OpenGL dependency is already causing I'd rather not introduce another, more specific dependency. I like the suggestion of adding the note about headless rendering to the README, though! I added a note in 083d743b73d43f38539212772dc8b3244e237f92.
