### ISSUE TITLE
Single shape reconstruction 

### ISSUE THREAD

**Issue by HM102** [facebookresearch/DeepSDF#22]
Can you provide the reconstruction code for single shape with no latent vector. Given the predicted SDF; reconstruct the mesh. Is there a way to turn off the latent vector in reconstruction, in the current code?

**Comment by tschmidt23** [comment]
Currently there is no way to turn off the latent vector. You can set the learning rate for the latent vector to 0 but that's not quite the same. I'll consider supporting this feature if I get a chance.

**Comment by yd-yin** [comment]
Hi! Is there any architecture & training paremeters & data preprocessing difference between the main experiment setup and the single shape reconstruction?
