### ISSUE TITLE
Preprocessing error

### ISSUE THREAD

**Issue by WordBearerYI** [facebookresearch/DeepSDF#25]
Preprocess part gives me quite a headache. I have the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
DeepSdf - INFO - ShapeNetCore.v2/04256520/45d3384ab8d5b6295637fc0f4b98e88b/models/model_normalized.obj --> data/SdfSamples/ShapeNetV2/04256520/45d3384ab8d5b6295637fc0f4b98e88b.npz
Unable to read texture 'texture_0'
Unable to read texture 'texture_2'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
Unable to read texture 'texture_2'
Unable to read texture 'texture_4'
Unable to read texture 'texture_5'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
DeepSdf - INFO - ShapeNetCore.v2/04256520/45d96e52f535907d40c4baf1afd9784/models/model_normalized.obj --> data/SdfSamples/ShapeNetV2/04256520/45d96e52f535907d40c4baf1afd9784.npz

I run this on a remote GPU server. Previously, I resolved X11 can't open display X by enabling X11 forwarding on client-side.  Now it gives me this kind of message and still generates 0 output.  I have no idea how to fix this.

- Ubuntu 16.04.5 LTS
- Pangolin cloned and built with the master branch.

**Comment by JUN-TSUZUKI** [comment]
I have the same error.
This program doesn't generate ".npz" data

**Comment by CuiLily** [comment]
Does anyone have any solutions?

**Comment by Yi-Shi94** [comment]
For running it on a remote server, no.

**Comment by Yi-Shi94** [comment]
> Does anyone have any solutions?

I think if you run it under a local machine, It may work.

**Comment by CuiLily** [comment]
> > Does anyone have any solutions?
> 
> I think if you run it under a local machine, It may work.

I run it under the local machine,  but it still doesn't work. Do you have solutions?

**Comment by tschmidt23** [comment]
This error occurs when the platform does not have proper support for the GLX extension. As I mentioned in the comments on issue #35 I wouldn't necessarily expect certain setups such as remote VMs to be capable of running the OpenGL components of the preprocessing code. @WordBearerYI , have you tried running in headless mode by setting the environment variable mentioned in the README?

**Comment by 1995YogeshSharma** [comment]
I was able to generate .npz files even on remote server 
use 
`export PANGOLIN_WINDOW_URI=headless://`
Also, make sure the remote server has graphics nvidia drivers running.

**Comment by DerekGrant** [comment]
> 

This indeed solved the X display problem but leads to new problem #95 
`
GLSL Program link failed: No details provided.
`
I am running on a remote server.
