### ISSUE TITLE
【Error】preprocess_data.py

### ISSUE THREAD

**Issue by JUN-TSUZUKI** [facebookresearch/DeepSDF#27]
When I execute "preprocess_data.py", I found following error.
   python3 preprocess_data.py --data_dir data -s ../Dataset/ShapeNetCore.v2/ --name ShapeNetV2 --split examples/splits/sv2_sofas_train.json  --skip

../Dataset/ShapeNetCore.v2/04256520/152161d238fbc55d41cf86c757faf4f9/../Dataset/ShapeNetCore.v2/04256520/152161d238fbc55d41cf86c757faf4f9/models/model_normalized.obj
DeepSdf - INFO - ../Dataset/ShapeNetCore.v2/04256520/152161d238fbc55d41cf86c757faf4f9/../Dataset/ShapeNetCore.v2/04256520/152161d238fbc55d41cf86c757faf4f9/models/model_normalized.obj --> data/SdfSamples/ShapeNetV2/04256520/152161d238fbc55d41cf86c757faf4f9.npz
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to load OBJ file '../Dataset/ShapeNetCore.v2/04256520/14aa542942c9ef1264dd558a50c0650d/../Dataset/ShapeNetCore.v2/04256520/14aa542942c9ef1264dd558a50c0650d/models/model_normalized.obj'. Error: 'Cannot open file [../Dataset/ShapeNetCore.v2/04256520/14aa542942c9ef1264dd558a50c0650d/../Dataset/ShapeNetCore.v2/04256520/14aa542942c9ef1264dd558a50c0650d/models/model_normalized.obj]

**Comment by JUN-TSUZUKI** [comment]
I correct shape_dir path

**Comment by tovacinni** [comment]
What did you do to correct shape_dir? @JUN-TSUZUKI

**Comment by CuiLily** [comment]
how do you fix the problem?

**Comment by haomengz** [comment]
@CuiLily @JUN-TSUZUKI @tovacinni Hi! I am running the model these days and I meet the same problems. Have you figured it out before? I think there should be some problems in the path.

**Comment by frasermarch** [comment]
Anyone manage to fix this?

**Comment by frasermarch** [comment]
@JUN-TSUZUKI

**Comment by frasermarch** [comment]
Anyone manage to fix this? @JUN-TSUZUKI

**Comment by frasermarch** [comment]
I fixed it. The shape directory has to be an absolute file path
