### ISSUE TITLE
OpenGL Error: XX (500) and   what():  Interlace not yet supported

### ISSUE THREAD

**Issue by lilizaimumu** [facebookresearch/DeepSDF#5]
When running preprocess_data.py, two error occured:
DeepSdf - INFO - /home/mpl/ShapeNetCore.v2/03001627/df7fc0b3b796714fd00dd29272c1070b/models/model_normalized.obj --> /home/mpl/DeepSDF/data/SurfaceSamples/ShapeNetV2/03001627/df7fc0b3b796714fd00dd29272c1070b.ply
terminate called after throwing an instance of 'std::runtime_error'
  what():  Interlace not yet supported
DeepSdf - INFO - /home/mpl/ShapeNetCore.v2/03001627/df8311076b838c7ea5f9d52c12457194/models/model_normalized.obj --> /home/mpl/DeepSDF/data/SurfaceSamples/ShapeNetV2/03001627/df8311076b838c7ea5f9d52c12457194.ply
OpenGL Error: XX (500)
In: /usr/local/include/pangolin/gl/gl.hpp, line 203
DeepSdf - INFO - /home/mpl/ShapeNetCore.v2/03001627/df8374d8f3563be8f1783a44a88d6274/models/model_normalized.obj --> /home/mpl/DeepSDF/data/SurfaceSamples/ShapeNetV2/03001627/df8374d8f3563be8f1783a44a88d6274.ply

**Comment by tschmidt23** [comment]
This is caused by an incompatibility between the textures in ShapeNet and Pangolin, which has just this morning been resolved. Please update your Pangolin making sure you are on top of commit 57ee5fc7398a35c2a1574ea51000279665fcbc67 and this should work!

**Comment by lilizaimumu** [comment]
I've updated Pangolin to the latest version,but the problem still occured:
Unable to read texture 'texture_0'
OpenGL Error: XX (500)
In: /usr/local/include/pangolin/gl/gl.hpp, line 203

**Comment by JiamingSuen** [comment]
I'm also getting this "OpenGL Error: XX (500)" error even after I updated to the latest version of Pangolin. I also confirmed that this does affect the generation since not all models have the corresponding generated npz file.
@tschmidt23 Would you please give more details about your environment? Such as OS version, OpenGL version etc. Thanks!

**Comment by tschmidt23** [comment]
Hi @lilizaimumu, with the change to Pangolin it will print a warning if a texture cannot be read but, because the textures are not needed for SDF sampling, it may be the case that the sampling still succeeded. Check the data directory for the corresponding shape to verify. @JiamingSuen, the script will write nothing if it fails so if you see the .npz files then everything should be good to go!

**Comment by lilizaimumu** [comment]
> Hi @lilizaimumu, with the change to Pangolin it will print a warning if a texture cannot be read but, because the textures are not needed for SDF sampling, it may be the case that the sampling still succeeded. Check the data directory for the corresponding shape to verify. @JiamingSuen, the script will write nothing if it fails so if you see the .npz files then everything should be good to go!

@tschmidt23  Hi, after runing preprocess_data.py, there are only 165 npz files in the data directory, but sv2_chairs_train.json includes more than 3000 examples. Does this happen because of OpenGL Error:XX(500)?

**Comment by JiamingSuen** [comment]
@tschmidt23 That's good to know, thanks!
I have a few more questions:

1. Do you plan to release the pretrained model for each class?
2. I noticed that in the video demo you also present the result of the 'vehicle' class(not in the paper experiments though), would you please share the splits for vehicles as well? Or the scripts to generate these split files(selecting watertight models according to the paper) would be better.

Thanks a lot!

**Comment by yxw9636** [comment]
> > Hi @lilizaimumu, with the change to Pangolin it will print a warning if a texture cannot be read but, because the textures are not needed for SDF sampling, it may be the case that the sampling still succeeded. Check the data directory for the corresponding shape to verify. @JiamingSuen, the script will write nothing if it fails so if you see the .npz files then everything should be good to go!
> 
> @tschmidt23 Hi, after runing preprocess_data.py, there are only 165 npz files in the data directory, but sv2_chairs_train.json includes more than 3000 examples. Does this happen because of OpenGL Error:XX(500)?

I switched to dataset ShapeNetCore.v1, and I also met with this error:
```
OpenGL Error: XX (500)
In: /usr/local/include/pangolin/gl/gl.hpp, line 203
```
and after I finished the code, it only has 150 .npz files in the directory instead of ~3000 examples.

**Comment by sunglyoungKim** [comment]
Hello,
I am having the same error and I have 1600 npz files out of 3000+ sofa examples. Could you give some thought about?

Also, could you share how many and what GPUs are used when you train the model? Thank you

**Comment by tschmidt23** [comment]
Hi @sunglyoungKim, that is approximately the expected number of sofas in the training split. As alluded to by @jjparkcv [here](https://github.com/facebookresearch/DeepSDF/issues/8#issuecomment-518414250), not all of the shapes are able to be processed, so we provided lists of shapes that should work. There should be one .npz file per shape in the list that you pass to the preprocessing script.

**Comment by csyhping** [comment]
> Hello,
> I am having the same error and I have 1600 npz files out of 3000+ sofa examples. Could you give some thought about?
> 
> Also, could you share how many and what GPUs are used when you train the model? Thank you

Could u plz provide one example of the .npz files? There is no .npz file for me after running the preprocess.py, thanks .

**Comment by csyhping** [comment]
> Hello,
> I am having the same error and I have 1600 npz files out of 3000+ sofa examples. Could you give some thought about?
> 
> Also, could you share how many and what GPUs are used when you train the model? Thank you

@sunglyoungKim Could u plz provide one example of the .npz files? There is no .npz file for me after running the preprocess.py, thanks .
