### ISSUE TITLE
Question about the number of categories related to the network.

### ISSUE THREAD

**Issue by taeyeopl** [facebookresearch/DeepSDF#69]
Thanks for sharing good work!

I have a simple question about your work. 
Q1. Dose DeepSDF covers all the categories (ex. chair, plane, table, lamp, sofa) of one network? 
Or Does It requires one class per one network for training and inference??

**Comment by amaleki2** [comment]
Given there are different config files for different classes in the example folder, I suspect there should be one model per class.

**Comment by taeyeopl** [comment]
@amaleki2  Thanks for your replry.
