### ISSUE TITLE
EGL init failed

### ISSUE THREAD

**Issue by QtEngineer** [facebookresearch/DeepSDF#90]
DeepSdf - INFO - /root/autodl-tmp/ShapeNetCore.v2/02691156/16079ddc92f4c9efd677715e63c14038/models/model_normalized.obj --> data/SdfSamples/ShapeNetV2/02691156/16079ddc92f4c9efd677715e63c14038.npz
EGL init failed
Cannot create EGL surface
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by AnimeshSinha1309** [comment]
I am facing the same issue. @QtEngineer any suggestions on how to resolve?
